columns:
  - name: char
    type: BIGINT
  - name: level
    type: BIGINT
  - name: race
    type: VARCHAR
  - name: charclass
    type: VARCHAR
  - name: zone
    type: VARCHAR
  - name: guild
    type: BIGINT
  - name: timestamp
    type: TIMESTAMP
