columns:
  - name: maker
    type: VARCHAR
  - name: model
    type: VARCHAR
  - name: mileage
    type: BIGINT
  - name: manufacture_year
    type: BIGINT
  - name: engine_displacement
    type: BIGINT
  - name: engine_power
    type: BIGINT
  - name: body_type
    type: VARCHAR
  - name: color_slug
    type: VARCHAR
  - name: stk_year
    type: VARCHAR
  - name: transmission
    type: VARCHAR
  - name: door_count
    type: VARCHAR
  - name: seat_count
    type: VARCHAR
  - name: fuel_type
    type: VARCHAR
  - name: date_created
    type: TIMESTAMP
  - name: date_last_seen
    type: TIMESTAMP
  - name: price_eur
    type: DOUBLE
