columns:
  - name: station_id
    type: BIGINT
  - name: station_name
    type: VARCHAR
  - name: station_country
    type: VARCHAR
  - name: YEAR
    type: BIGINT
  - name: observation_date
    type: TIMESTAMP
  - name: latitude
    type: DOUBLE
  - name: longitude
    type: DOUBLE
  - name: elevation
    type: DOUBLE
  - name: wind_direction_angle
    type: BIGINT
  - name: wind_direction_angle_units
    type: VARCHAR
  - name: wind_direction_quality
    type: VARCHAR
  - name: wind_type
    type: VARCHAR
  - name: wind_speed_rate
    type: DOUBLE
  - name: wind_speed_rate_units
    type: VARCHAR
  - name: wind_speed_quality
    type: VARCHAR
  - name: sky_ceiling_height
    type: BIGINT
  - name: sky_ceiling_height_units
    type: VARCHAR
  - name: sky_ceiling_quality
    type: VARCHAR
  - name: sky_ceiling_determination
    type: VARCHAR
  - name: sky_cavok
    type: VARCHAR
  - name: visibility_distance
    type: BIGINT
  - name: visibility_distance_units
    type: VARCHAR
  - name: visibility_distance_quality
    type: VARCHAR
  - name: visibility_variability
    type: VARCHAR
  - name: visibility_variability_quality
    type: VARCHAR
  - name: air_temperature
    type: DOUBLE
  - name: air_temperature_units
    type: VARCHAR
  - name: air_temperature_quality
    type: VARCHAR
  - name: air_temperature_dew_point
    type: BIGINT
  - name: air_temperature_dew_point_units
    type: VARCHAR
  - name: air_temperature_dew_point_quality
    type: VARCHAR
  - name: atmospheric_sea_level_pressure
    type: DOUBLE
  - name: atmospheric_sea_level_pressure_units
    type: VARCHAR
  - name: atmospheric_sea_level_pressure_quality
    type: VARCHAR
  - name: GEOPOINT
    type: VARCHAR
