columns:
  - name: col1
    type: BIGINT
  - name: ID
    type: BIGINT
  - name: Case Number
    type: VARCHAR
  - name: Date
    type: TIMESTAMP
  - name: Block
    type: VARCHAR
  - name: IUCR
    type: VARCHAR
  - name: Primary Type
    type: VARCHAR
  - name: Description
    type: VARCHAR
  - name: Location Description
    type: VARCHAR
  - name: Arrest
    type: BOOLEAN
  - name: Domestic
    type: BOOLEAN
  - name: Beat
    type: BIGINT
  - name: District
    type: DOUBLE
  - name: Ward
    type: DOUBLE
  - name: Community Area
    type: DOUBLE
  - name: FBI Code
    type: VARCHAR
  - name: X Coordinate
    type: DOUBLE
  - name: Y Coordinate
    type: DOUBLE
  - name: Year
    type: BIGINT
  - name: Updated On
    type: TIMESTAMP
  - name: Latitude
    type: DOUBLE
  - name: Longitude
    type: DOUBLE
  - name: Location
    type: VARCHAR
