columns:
  - name: train_id
    type: VARCHAR
  - name: status
    type: BIGINT
  - name: next_station
    type: VARCHAR
  - name: service
    type: VARCHAR
  - name: dest
    type: VARCHAR
  - name: lon
    type: DOUBLE
  - name: lat
    type: DOUBLE
  - name: source
    type: VARCHAR
  - name: track_change
    type: VARCHAR
  - name: track
    type: VARCHAR
  - name: date
    type: DATE
  - name: timeStamp0
    type: TIMESTAMP
  - name: timeStamp1
    type: TIMESTAMP
  - name: seconds
    type: BIGINT
