columns:
  - name: add_these_pw_job_title_9089
    type: VARCHAR
  - name: agent_city
    type: VARCHAR
  - name: agent_firm_name
    type: VARCHAR
  - name: agent_state
    type: VARCHAR
  - name: application_type
    type: VARCHAR
  - name: case_no
    type: VARCHAR
  - name: case_number
    type: VARCHAR
  - name: case_received_date
    type: VARCHAR
  - name: case_status
    type: VARCHAR
  - name: class_of_admission
    type: VARCHAR
  - name: country_of_citizenship
    type: VARCHAR
  - name: country_of_citzenship
    type: VARCHAR
  - name: decision_date
    type: DATE
  - name: employer_address_1
    type: VARCHAR
  - name: employer_address_2
    type: VARCHAR
  - name: employer_city
    type: VARCHAR
  - name: employer_country
    type: VARCHAR
  - name: employer_decl_info_title
    type: VARCHAR
  - name: employer_name
    type: VARCHAR
  - name: employer_num_employees
    type: VARCHAR
  - name: employer_phone
    type: VARCHAR
  - name: employer_phone_ext
    type: VARCHAR
  - name: employer_postal_code
    type: VARCHAR
  - name: employer_state
    type: VARCHAR
  - name: employer_yr_estab
    type: VARCHAR
  - name: foreign_worker_info_alt_edu_experience
    type: VARCHAR
  - name: foreign_worker_info_birth_country
    type: VARCHAR
  - name: foreign_worker_info_city
    type: VARCHAR
  - name: foreign_worker_info_education
    type: VARCHAR
  - name: foreign_worker_info_education_other
    type: VARCHAR
  - name: foreign_worker_info_inst
    type: VARCHAR
  - name: foreign_worker_info_major
    type: VARCHAR
  - name: foreign_worker_info_postal_code
    type: VARCHAR
  - name: foreign_worker_info_rel_occup_exp
    type: VARCHAR
  - name: foreign_worker_info_req_experience
    type: VARCHAR
  - name: foreign_worker_info_state
    type: VARCHAR
  - name: foreign_worker_info_training_comp
    type: VARCHAR
  - name: foreign_worker_ownership_interest
    type: VARCHAR
  - name: foreign_worker_yr_rel_edu_completed
    type: VARCHAR
  - name: fw_info_alt_edu_experience
    type: VARCHAR
  - name: fw_info_birth_country
    type: VARCHAR
  - name: fw_info_education_other
    type: VARCHAR
  - name: fw_info_postal_code
    type: VARCHAR
  - name: fw_info_rel_occup_exp
    type: VARCHAR
  - name: fw_info_req_experience
    type: VARCHAR
  - name: fw_info_training_comp
    type: VARCHAR
  - name: fw_info_yr_rel_edu_completed
    type: VARCHAR
  - name: fw_ownership_interest
    type: VARCHAR
  - name: ji_foreign_worker_live_on_premises
    type: VARCHAR
  - name: ji_fw_live_on_premises
    type: VARCHAR
  - name: ji_live_in_dom_svc_contract
    type: VARCHAR
  - name: ji_live_in_domestic_service
    type: VARCHAR
  - name: ji_offered_to_sec_j_foreign_worker
    type: VARCHAR
  - name: ji_offered_to_sec_j_fw
    type: VARCHAR
  - name: job_info_alt_cmb_ed_oth_yrs
    type: VARCHAR
  - name: job_info_alt_combo_ed
    type: VARCHAR
  - name: job_info_alt_combo_ed_exp
    type: VARCHAR
  - name: job_info_alt_combo_ed_other
    type: VARCHAR
  - name: job_info_alt_field
    type: VARCHAR
  - name: job_info_alt_field_name
    type: VARCHAR
  - name: job_info_alt_occ
    type: VARCHAR
  - name: job_info_alt_occ_job_title
    type: VARCHAR
  - name: job_info_alt_occ_num_months
    type: VARCHAR
  - name: job_info_combo_occupation
    type: VARCHAR
  - name: job_info_education
    type: VARCHAR
  - name: job_info_education_other
    type: VARCHAR
  - name: job_info_experience
    type: VARCHAR
  - name: job_info_experience_num_months
    type: VARCHAR
  - name: job_info_foreign_ed
    type: VARCHAR
  - name: job_info_foreign_lang_req
    type: VARCHAR
  - name: job_info_job_req_normal
    type: VARCHAR
  - name: job_info_job_title
    type: VARCHAR
  - name: job_info_major
    type: VARCHAR
  - name: job_info_training
    type: VARCHAR
  - name: job_info_training_field
    type: VARCHAR
  - name: job_info_training_num_months
    type: VARCHAR
  - name: job_info_work_city
    type: VARCHAR
  - name: job_info_work_postal_code
    type: VARCHAR
  - name: job_info_work_state
    type: VARCHAR
  - name: naics_2007_us_code
    type: VARCHAR
  - name: naics_2007_us_title
    type: VARCHAR
  - name: naics_code
    type: VARCHAR
  - name: naics_title
    type: VARCHAR
  - name: naics_us_code
    type: VARCHAR
  - name: naics_us_code_2007
    type: VARCHAR
  - name: naics_us_title
    type: VARCHAR
  - name: naics_us_title_2007
    type: VARCHAR
  - name: orig_case_no
    type: VARCHAR
  - name: orig_file_date
    type: VARCHAR
  - name: preparer_info_emp_completed
    type: VARCHAR
  - name: preparer_info_title
    type: VARCHAR
  - name: pw_amount_9089
    type: DOUBLE
  - name: pw_determ_date
    type: VARCHAR
  - name: pw_expire_date
    type: VARCHAR
  - name: pw_job_title_908
    type: VARCHAR
  - name: pw_job_title_9089
    type: VARCHAR
  - name: pw_level_9089
    type: VARCHAR
  - name: pw_soc_code
    type: VARCHAR
  - name: pw_soc_title
    type: VARCHAR
  - name: pw_source_name_9089
    type: VARCHAR
  - name: pw_source_name_other_9089
    type: VARCHAR
  - name: pw_track_num
    type: VARCHAR
  - name: pw_unit_of_pay_9089
    type: VARCHAR
  - name: rec_info_barg_rep_notified
    type: VARCHAR
  - name: recr_info_barg_rep_notified
    type: VARCHAR
  - name: recr_info_coll_teach_comp_proc
    type: VARCHAR
  - name: recr_info_coll_univ_teacher
    type: VARCHAR
  - name: recr_info_employer_rec_payment
    type: VARCHAR
  - name: recr_info_first_ad_start
    type: VARCHAR
  - name: recr_info_job_fair_from
    type: VARCHAR
  - name: recr_info_job_fair_to
    type: VARCHAR
  - name: recr_info_on_campus_recr_from
    type: VARCHAR
  - name: recr_info_on_campus_recr_to
    type: VARCHAR
  - name: recr_info_pro_org_advert_from
    type: VARCHAR
  - name: recr_info_pro_org_advert_to
    type: VARCHAR
  - name: recr_info_prof_org_advert_from
    type: VARCHAR
  - name: recr_info_prof_org_advert_to
    type: VARCHAR
  - name: recr_info_professional_occ
    type: VARCHAR
  - name: recr_info_radio_tv_ad_from
    type: VARCHAR
  - name: recr_info_radio_tv_ad_to
    type: VARCHAR
  - name: recr_info_second_ad_start
    type: VARCHAR
  - name: recr_info_sunday_newspaper
    type: VARCHAR
  - name: recr_info_swa_job_order_end
    type: VARCHAR
  - name: recr_info_swa_job_order_start
    type: VARCHAR
  - name: refile
    type: VARCHAR
  - name: ri_1st_ad_newspaper_name
    type: VARCHAR
  - name: ri_2nd_ad_newspaper_name
    type: VARCHAR
  - name: ri_2nd_ad_newspaper_or_journal
    type: VARCHAR
  - name: ri_campus_placement_from
    type: VARCHAR
  - name: ri_campus_placement_to
    type: VARCHAR
  - name: ri_coll_tch_basic_process
    type: VARCHAR
  - name: ri_coll_teach_pro_jnl
    type: VARCHAR
  - name: ri_coll_teach_select_date
    type: VARCHAR
  - name: ri_employee_referral_prog_from
    type: VARCHAR
  - name: ri_employee_referral_prog_to
    type: VARCHAR
  - name: ri_employer_web_post_from
    type: VARCHAR
  - name: ri_employer_web_post_to
    type: VARCHAR
  - name: ri_job_search_website_from
    type: VARCHAR
  - name: ri_job_search_website_to
    type: VARCHAR
  - name: ri_layoff_in_past_six_months
    type: VARCHAR
  - name: ri_local_ethnic_paper_from
    type: VARCHAR
  - name: ri_local_ethnic_paper_to
    type: VARCHAR
  - name: ri_posted_notice_at_worksite
    type: VARCHAR
  - name: ri_pvt_employment_firm_from
    type: VARCHAR
  - name: ri_pvt_employment_firm_to
    type: VARCHAR
  - name: ri_us_workers_considered
    type: VARCHAR
  - name: schd_a_sheepherder
    type: VARCHAR
  - name: us_economic_sector
    type: VARCHAR
  - name: wage_offer_from_9089
    type: DOUBLE
  - name: wage_offer_to_9089
    type: DOUBLE
  - name: wage_offer_unit_of_pay_9089
    type: VARCHAR
  - name: wage_offered_from_9089
    type: VARCHAR
  - name: wage_offered_to_9089
    type: VARCHAR
  - name: wage_offered_unit_of_pay_9089
    type: VARCHAR
