columns:
  - name: EIN
    type: VARCHAR
  - name: NAME
    type: VARCHAR
  - name: ICO
    type: VARCHAR
  - name: STREET
    type: VARCHAR
  - name: CITY
    type: VARCHAR
  - name: STATE
    type: VARCHAR
  - name: ZIP
    type: VARCHAR
  - name: GROUP
    type: VARCHAR
  - name: SUBSECTION
    type: VARCHAR
  - name: AFFILIATION
    type: BIGINT
  - name: CLASSIFICATION
    type: VARCHAR
  - name: RULING
    type: VARCHAR
  - name: DEDUCTIBILITY
    type: BIGINT
  - name: FOUNDATION
    type: VARCHAR
  - name: ACTIVITY
    type: VARCHAR
  - name: ORGANIZATION
    type: BIGINT
  - name: STATUS
    type: VARCHAR
  - name: TAX_PERIOD
    type: BIGINT
  - name: ASSET_CD
    type: BIGINT
  - name: INCOME_CD
    type: BIGINT
  - name: FILING_REQ_CD
    type: VARCHAR
  - name: PF_FILING_REQ_CD
    type: BIGINT
  - name: ACCT_PD
    type: VARCHAR
  - name: ASSET_AMT
    type: BIGINT
  - name: INCOME_AMT
    type: BIGINT
  - name: REVENUE_AMT
    type: BIGINT
  - name: NTEE_CD
    type: VARCHAR
  - name: SORT_NAME
    type: VARCHAR
