name: CSV Size Report

on:
  push:
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install make
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      # Set FASTLANES_DATA_DIR to repo root
      - name: Set FASTLANES_DATA_DIR environment variable
        run: echo "FASTLANES_DATA_DIR=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      - name: Generate CSV size report
        run: make csv_size_report

      - name: Show generated CSV
        run: |
          echo "→ csv_sizes_report.csv contents:"
          cat csv_sizes_report.csv

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: csv-size-report
          path: csv_sizes_report.csv
